services:
  backend:
    build: ./
    container_name: bd_server_container
    working_dir: /bd_server
    ports:
      - "8000:8015"
    env_file:
      - .env
    environment:
      DOCKER: "1"
    command:
      - ./commands/start_server_dev.sh
    volumes:
      - ./src:/bd_server/src
      - ./commands:/bd_server/commands
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:17.5
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  pg_data: { }
