# Generated by Django 5.2.1 on 2025-07-13 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0005_order_delete_orderrequest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Email"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="full_name",
            field=models.CharField(max_length=150, verbose_name="Повне імʼя"),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Створений"),
                    ("in_progress", "Опрацьовується"),
                    ("completed", "Виконаний"),
                ],
                default="created",
                max_length=20,
            ),
        ),
    ]
