# Generated by Django 5.2.1 on 2025-07-13 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0006_alter_order_email_alter_order_full_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="basketitem",
            options={"ordering": ["id"]},
        ),
    ]
