# Generated by Django 5.2.1 on 2025-07-13 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0007_alter_basketitem_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="discount",
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="item",
            name="new_collection",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Створений"),
                    ("in_progress", "Опрацьовується"),
                    ("completed", "Виконаний"),
                    ("cancelled", "Скасований"),
                ],
                default="created",
                max_length=20,
            ),
        ),
    ]
