# Generated by Django 5.2.1 on 2025-07-14 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0009_itemcolor_itemimage_itemsize"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="itemcolor",
            name="hex_code",
        ),
    ]
