# Generated by Django 5.2.1 on 2025-07-14 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0010_remove_itemcolor_hex_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="itemcolor",
            name="item",
        ),
        migrations.RemoveField(
            model_name="itemsize",
            name="item",
        ),
        migrations.AddField(
            model_name="item",
            name="colors",
            field=models.ManyToManyField(
                blank=True, related_name="items", to="shop.itemcolor"
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="sizes",
            field=models.ManyToManyField(
                blank=True, related_name="items", to="shop.itemsize"
            ),
        ),
    ]
