# Generated by Django 5.2.1 on 2025-07-14 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0011_remove_itemcolor_item_remove_itemsize_item_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="basketitem",
            name="selected_color",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="basketitem",
            name="selected_size",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
