# Generated by Django 5.2.1 on 2025-05-27 12:34

import multiselectfield.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "plan_name",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("group", "Абонемент"),
                            ("person", "Індивідуальне тренування"),
                        ],
                        default="group",
                        max_length=120,
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, max_length=500, null=True),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "schedule_day",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                (
                    "schedule_days",
                    multiselectfield.db.fields.MultiSelectField(
                        choices=[
                            ("mon", "Понеділок"),
                            ("tue", "Вівторок"),
                            ("wed", "Середа"),
                            ("thu", "Четвер"),
                            ("fri", "Пʼятниця"),
                            ("sat", "Субота"),
                            ("sun", "Неділя"),
                        ],
                        max_length=30,
                    ),
                ),
                ("schedule_time", models.TimeField(blank=True, null=True)),
                ("trainer", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "users",
                    models.ManyToManyField(
                        blank=True,
                        related_name="dance_groups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
