# Generated by Django 5.2.1 on 2025-05-31 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trainings", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="group",
            name="schedule_day",
        ),
    ]
