# Generated by Django 5.2.1 on 2025-06-02 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainings", "0002_remove_group_schedule_day"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=0, max_digits=10, null=True
            ),
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day",
                    models.CharField(
                        choices=[
                            ("mon", "Понеділок"),
                            ("tue", "Вівторок"),
                            ("wed", "Середа"),
                            ("thu", "Четвер"),
                            ("fri", "Пʼятниця"),
                            ("sat", "Субота"),
                            ("sun", "Неділя"),
                        ],
                        max_length=10,
                    ),
                ),
                ("time", models.TimeField()),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="trainings.group",
                    ),
                ),
            ],
        ),
    ]
