# Generated by Django 5.2.1 on 2025-06-02 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trainings", "0005_schedule"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="group",
            name="schedule_days",
        ),
        migrations.RemoveField(
            model_name="group",
            name="schedule_time",
        ),
    ]
