# Generated by Django 5.2.1 on 2025-06-06 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainings", "0008_alter_group_plan_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="plan_name",
            field=models.CharField(
                blank=True,
                choices=[("0", "Абонемент"), ("1", "Індивідуальне тренування")],
                default="0",
                max_length=120,
                null=True,
            ),
        ),
    ]
