# Generated by Django 5.2.1 on 2025-07-15 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainings", "0009_alter_group_plan_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="schedule",
            name="group",
        ),
        migrations.AddField(
            model_name="group",
            name="schedules",
            field=models.ManyToManyField(
                blank=True, related_name="groups", to="trainings.schedule"
            ),
        ),
    ]
