# Generated by Django 5.2.1 on 2025-05-25 12:15

from django.db import migrations

import accounts.managers


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", accounts.managers.CustomUserManager()),
            ],
        ),
        migrations.RenameField(
            model_name="user",
            old_name="is_admin",
            new_name="is_staff",
        ),
    ]
