# Generated by Django 5.2.1 on 2025-05-27 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_managers_rename_is_admin_user_is_staff"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Group",
        ),
    ]
