# Generated by Django 5.2.1 on 2025-06-09 06:16

from django.db import migrations, models

import accounts.utils


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_delete_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(blank=True, max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Designates whether this user should be treated as active.Unselect this instead of deleting accounts.",
                verbose_name="active",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=accounts.utils.user_photo_path,
                verbose_name="photo",
            ),
        ),
    ]
