server {
    listen 80 default_server;
    listen 443 default_server;

    server_name bondini_dance;

    location /static/ {
        alias /bd_server/src/static/;
    }

    location /media/ {
        alias /bd_server/src/media/;
    }

    location / {
        proxy_pass http://backend:8015;
        proxy_set_header Host $host;
    }
}
